### ISSUE TITLE
Does it possible to increase IMU sample rate?

### ISSUE THREAD

**Issue by lixinghe1999** [yahyatawil/BMI270_AUX_BMM150#1]
Dear everyone,

I am trying to use the examples/interrupts, however, the sample rate can not go above 200 Hz, when I set it to 400 Hz, the real sample rate is still 200Hz.

Has anyone worked on it?

Thanks in advance for your help!

**Comment by yahyatawil** [comment]
Hi 

Generly speaking you need to check the following: 

1- Use an osciloscope to see the interrupt pin from the BMI270 and check if the interrupt are changing or not. 
2- The MCU/firmware you are using is not resposive enough more than 200Hz (this is incase you are calulating the sample rate from the firmware). 
3- I did not tested the sample rate before, but the way Arduino cores are designed usually add slowness to the execution time which may limits the interrupt speed which downgrad the sample rates.

If nothing fron the three item above worked for you, then I advice you to enable the FIFO buffer which allows you process less inteuuprts, while saving data in the buffer. Please check section 4.7 from BMI270 datasheet. However the FIFO is not supported in the library yet.
